name: Deploy Foxy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy to server
        run: |
            echo "${{secrets.SSH_PRIVATE_KEY}}" > deploy_key
            chmod 600 deploy_key
            ssh -i deploy_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
                cd /home/foxy/Foxy
                git pull origin master
                yarn
                yarn build:client
                yarn build:server
                pm2 restart 0 && pm2 restart 2
            EOF